#ifndef RFUZZ_HARNESS_H
#define RFUZZ_HARNESS_H

#include "Vtop_module.h"

// Fuzz Harness
// Generated by Pyverilog script
// Give signals values in one cycle from the bitstream
int fuzz_poke();

#endif // RFUZZ_HARNESS_H
